---
- name: Set up Nginx web server and deploy a default web page
  hosts: all  # Replace with your target group or host name
  tasks:

    - name: Gather facts
      ansible.builtin.setup:
      
    - name: Install Nginx package
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx package
      ansible.builtin.yum:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create the default index.html page for Debian
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head><title>Welcome to Nginx!</title></head>
            <body>
              <h1>Hello, World! This is the default page served by Nginx.</h1>
            </body>
          </html>
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Create the default index.html page for Redhat
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
            <head><title>Welcome to Nginx!</title></head>
            <body>
              <h1>Hello, World! This is the default page served by Nginx.</h1>
            </body>
          </html>
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
